<a href="https://colab.research.google.com/github/tohnperfect/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

## Array slicing

In [7]:
A[0,1]

2

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
A[:,:2]

array([[1, 2],
       [4, 5]])

In [11]:
A[1,1:]

array([5, 6])

### Distance matrix (Manhattan)

In [12]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [13]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX + distY

In [17]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:]) 

dist_mat_man 

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

## HW 6 
สร้าง Distance metrix (Euclidean) ของ data matrix ใน slides

โดยสร้าง function สำหรับคำนวณ Euclidean Distance